{
 "title": "Web",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "http://mit.edu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(exec.web_to_mit.output.time_total)"
    },
    {
     "target": "aliasByMetric(exec.web_to_mit.output.detail.*)"
    }
   ]
  },
  {
   "title": "http://localhost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(exec.web_to_localhost.output.time_total)"
    },
    {
     "target": "aliasByMetric(exec.web_to_localhost.output.detail.*)"
    }
   ]
  },
  {
   "title": "ping mit.edu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(exec.ping_to_mit.output, 'rtt')"
    }
   ]
  },
  {
   "title": "ping localhost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(exec.ping_to_localhost.output, 'rtt')"
    }
   ]
  }
 ]
}